// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_gpu_video_filters/test/generated.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:flutter_gpu_video_filters/src/messages/filter_messages.g.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FilterApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilterApi extends _i1.Mock implements _i2.FilterApi {
  MockFilterApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<int> create(
    String? vertexShader,
    String? fragmentShader,
    Map<String, double>? defaults,
    Map<String, _i5.Float64List>? arrays,
    List<String>? textures,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [
              vertexShader,
              fragmentShader,
              defaults,
              arrays,
              textures,
            ]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> exportVideoFile(
    int? filterId,
    bool? asset,
    String? input,
    String? output,
    String? format,
    int? period,
    int? height,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exportVideoFile, [
              filterId,
              asset,
              input,
              output,
              format,
              period,
              height,
            ]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> setFloatParameter(
    int? filterId,
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setFloatParameter, [filterId, key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setFloatArrayParameter(
    int? filterId,
    String? key,
    _i5.Float64List? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setFloatArrayParameter, [filterId, key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setBitmapParameter(
    int? filterId,
    String? key,
    _i5.Uint8List? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setBitmapParameter, [filterId, key, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setBitmapSourceParameter(
    int? filterId,
    String? key,
    bool? asset,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setBitmapSourceParameter, [
              filterId,
              key,
              asset,
              path,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dispose(int? filterId) =>
      (super.noSuchMethod(
            Invocation.method(#dispose, [filterId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [VideoPreviewApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoPreviewApi extends _i1.Mock implements _i2.VideoPreviewApi {
  MockVideoPreviewApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<int> create() =>
      (super.noSuchMethod(
            Invocation.method(#create, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> connect(int? textureId, int? filterId, bool? embedded) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [textureId, filterId, embedded]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect(int? textureId, bool? embedded) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [textureId, embedded]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setSource(
    int? textureId,
    String? path,
    bool? asset,
    bool? embedded,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setSource, [textureId, path, asset, embedded]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resume(int? textureId, bool? embedded) =>
      (super.noSuchMethod(
            Invocation.method(#resume, [textureId, embedded]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> pause(int? textureId, bool? embedded) =>
      (super.noSuchMethod(
            Invocation.method(#pause, [textureId, embedded]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dispose(int? textureId, bool? embedded) =>
      (super.noSuchMethod(
            Invocation.method(#dispose, [textureId, embedded]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getDuration(int? textureId, bool? embedded) =>
      (super.noSuchMethod(
            Invocation.method(#getDuration, [textureId, embedded]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getCurrentPosition(int? textureId, bool? embedded) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, [textureId, embedded]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> seekTo(int? textureId, bool? embedded, int? position) =>
      (super.noSuchMethod(
            Invocation.method(#seekTo, [textureId, embedded, position]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
